name: Build and Deploy

on:
  push:
    branches:
      - main  # Runs only when code is merged into `main`

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures the full history is fetched

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # Use your Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Commit and Push the `dist` folder
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -f dist
          git commit -m "Update dist folder after merge to main" || echo "No changes to commit"
          git push https://oauth2:${{ secrets.SERVERBYT_WORKFLOW_TOKEN }}@github.com/fayasPA/cyfletech.git main
